mj:
  discord:
    guild-id: 1094091138429886494
    channel-id: 1094091138874495097
    user-token: MTA1NTY3Njk0Mjg0MzY1NDI4NA.GtcFM6.TfbaQNgeBKY3iuGKl-2RzftZbSDo3-w-Pdqh1A
    user-wss: true
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
    id-prefix: "["
    id-suffix: "]"
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10
